[profile.release-size]
inherits = "release"
opt-level = "z"     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = "abort"     # Abort on panic
strip = true        # Automatically strip symbols from the binary.

[workspace]
members = [
    "lib/axum-header",
    "lib/axum-into-response",
    "lib/axum-s3",
    "lib/axum-s3-macros",
    "lib/axum-xml",
    "lib/ensure",
    "lib/serde-rename-chain",
    "lib/serde-s3",
    "lib/syn-utils",

    "main/entity",
    "main/migration",
    "main/minil",
    "main/service",
]
default-members = ["main/minil"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
axum = { version = "0.8.4", features = ["macros"] }
axum-core = "0.5.2"
axum-extra = { version = "0.10.1", features = ["query"] }
axum-test = "17.3.0"
bon = "3.6.4"
derive_more = { version = "2.0.1", features = ["full"] }
http = "1.3.1"
proc-macro2 = "1.0.95"
quote = "1.0.40"
sea-orm = { version = "1.1.12", features = ["debug-print", "runtime-tokio", "sqlite-use-returning-for-3_35", "sqlx-all"] }
sea-orm-migration = { version = "1.1.12", features = ["runtime-tokio", "sqlx-sqlite", "with-uuid"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_path_to_error = "0.1.17"
strum = { version = "0.27.1", features = ["derive"] }
syn = { version = "2.0.104", features = ["full"] }
tokio = { version = "1.45.1", features = ["full"] }
uuid = { version = "1.17.0", features = ["serde", "v4"] }

axum-header = { path = "lib/axum-header" }
axum-into-response = { path = "lib/axum-into-response" }
axum-s3 = { path = "lib/axum-s3" }
axum-s3-macros = { path = "lib/axum-s3-macros" }
axum-xml = { path = "lib/axum-xml" }
ensure = { path = "lib/ensure" }
serde-rename-chain = { path = "lib/serde-rename-chain", features = ["full"] }
serde-s3 = { path = "lib/serde-s3" }
syn-utils = { path = "lib/syn-utils" }

minil-entity = { path = "main/entity" }
minil-migration = { path = "main/migration" }
minil-service = { path = "main/service" }

aws-sdk-s3 = "1.93.0"
cache_control = "0.2.0"
