[workspace]
members = ["minil", "libs/*"]
default-members = ["minil"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
axum = "0.8.4"
axum-core = "0.5.2"
axum-test = "17.3.0"
derive_more = { version = "2.0.1", features = ["full"] }
http = "1.3.1"
proc-macro2 = "1.0.95"
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
serde_path_to_error = "0.1.17"
strum = { version = "0.27.1", features = ["derive"] }
syn = { version = "2.0.101", features = ["full"] }
thiserror = "2.0.12"
tokio = "1.45.0"

axum-header = { path = "libs/axum-header", features = ["extra"] }
axum-xml = { path = "libs/axum-xml" }
serde-rename-chain = { path = "libs/serde-rename-chain", features = ["full"] }
serde-s3 = { path = "libs/serde-s3" }
syn-utils = { path = "libs/syn-utils" }

aws-sdk-s3 = "1.88.0"
