ALTER TABLE chunk
    DROP CONSTRAINT fk_chunk_object;

ALTER TABLE chunk
    ADD CONSTRAINT fk_chunk_object
        FOREIGN KEY (object_id) REFERENCES OBJECT (id) ON
DELETE
CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE chunk
    DROP CONSTRAINT fk_chunk_part;

ALTER TABLE chunk
    ADD CONSTRAINT fk_chunk_part
        FOREIGN KEY (part_id) REFERENCES part (id) ON
DELETE
CASCADE DEFERRABLE INITIALLY DEFERRED;
