ALTER TABLE part
    DROP CONSTRAINT fk_part_version;

ALTER TABLE part
    ADD CONSTRAINT fk_part_version FOREIGN KEY (version_id) REFERENCES version(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
