ALTER TABLE tag
    DROP CONSTRAINT fk_tag_tag_set;

ALTER TABLE tag
    ADD CONSTRAINT fk_tag_tag_set FOREIGN KEY (tag_set_id) REFERENCES tag_set(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
