[package]
name = "minil"
version = "0.1.1"
edition.workspace = true

[dependencies]
hex = "0.4.3"
serde_plain = "1.0.2"
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.6", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

axum.workspace = true
derive_more.workspace = true
sea-orm.workspace = true
strum.workspace = true
tokio.workspace = true

digest.workspace = true
sha2.workspace = true

axum-extra.workspace = true
axum-s3.workspace = true
ensure.workspace = true
serde-s3.workspace = true

minil-migration.workspace = true
minil-service.workspace = true
