[package]
name = "minil"
version = "0.1.4"
edition.workspace = true

[dependencies]
base64 = "0.22.1"
futures = "0.3.31"
hex = "0.4.3"
paste = "1.0.15"
serde_plain = "1.0.2"
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.6", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

axum.workspace = true
axum-extra.workspace = true
axum-s3.workspace = true
derive_more.workspace = true
digest.workspace = true
ensure.workspace = true
sea-orm.workspace = true
serde-s3.workspace = true
sha2.workspace = true
strum.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true

minil-migration.workspace = true
minil-service.workspace = true
