[package]
name = "minil"
version = "0.1.1"
edition.workspace = true

[dependencies]
serde_plain = "1.0.2"
tokio-stream = { version = "0.1.17", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.6", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

crc-fast = "1.3.0"
md-5 = "0.10.6"
sha1 = "0.10.6"
sha2 = "0.10.9"

axum.workspace = true
derive_more.workspace = true
sea-orm.workspace = true
strum.workspace = true
tokio.workspace = true

axum-extra.workspace = true
axum-s3.workspace = true
ensure.workspace = true
serde-s3.workspace = true

minil-migration.workspace = true
minil-service.workspace = true

[dev-dependencies]
blake3.workspace = true
