[package]
name = "minil"
version = "0.1.0"
edition.workspace = true

[dependencies]
sha2 = "0.10.9"
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.6", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

entity.path = "../entity"
migration.path = "../migration"

axum.workspace = true
sea-orm.workspace = true
tokio.workspace = true

axum-s3.workspace = true
axum-extra.workspace = true
serde-s3.workspace = true
