[package]
name = "minil-migration"
version = "0.7.1"
edition.workspace = true

[dependencies]
sea-orm-migration.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
