[package]
name = "minil-service"
version = "0.2.0"
edition.workspace = true

[dependencies]
hex = "0.4.3"

axum.workspace = true
bytes.workspace = true
sea-orm.workspace = true
tokio-stream.workspace = true
uuid.workspace = true

infer = "0.19.0"
mime = "0.3.17"
mime_guess = "2.0.5"

crc-fast.workspace = true
digest.workspace = true
md-5.workspace = true
sha1.workspace = true
sha2.workspace = true

minil-entity.workspace = true
