[package]
name = "minil-service"
version = "0.1.6"
edition.workspace = true

[dependencies]
axum.workspace = true
sea-orm.workspace = true
tokio-stream.workspace = true
uuid.workspace = true

crc-fast.workspace = true
digest.workspace = true
md-5.workspace = true
sha1.workspace = true
sha2.workspace = true

minil-entity.workspace = true
