[package]
name = "minil-service"
version = "0.1.3"
edition.workspace = true

[dependencies]
tokio-stream = { version = "0.1.17", features = ["full"] }

axum.workspace = true
sea-orm.workspace = true
uuid.workspace = true

crc-fast.workspace = true
digest.workspace = true
md-5.workspace = true
sha1.workspace = true
sha2.workspace = true

minil-entity.workspace = true
