[package]
name = "minil-config"
version = "0.1.0"
edition.workspace = true

[dependencies]
config = "0.15.13"
smart-default = "0.7.1"

serde.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
